spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: 21dec253c3970dea135a7d1ce4e050a6
custom:
  paymentSecretKey: 'test_sk_jExPeJWYVQplpP1NdQKj349R5gvN:'